/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    pages: Page;
    skillsCollection: SkillsCollection;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    footer: Footer;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
  };
  login: {
    password: string;
    email: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  fallback?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'standard' | 'projects';
    standard?: {
      standardHero: {
        padding?: {
          paddingTop?: ('small' | 'medium' | 'large') | null;
          paddingBottom?: ('small' | 'medium' | 'large') | null;
        };
        position?: ('left' | 'right') | null;
        heading: string;
        content?: {
          richText?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          links?:
            | {
                link: {
                  label: string;
                  reference?: {
                    relationTo: 'pages';
                    value: string | Page;
                  } | null;
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  url?: string | null;
                  appearance?: ('default' | 'gradient') | null;
                };
                id?: string | null;
              }[]
            | null;
          imageLinks?:
            | {
                imageLink?: {
                  reference?: {
                    relationTo: 'pages';
                    value: string | Page;
                  } | null;
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  url?: string | null;
                  image?: string | Media | null;
                };
                id?: string | null;
              }[]
            | null;
        };
        heroImage: string | Media;
        enableBackgroundColors?: boolean | null;
        backgroundColors?: {
          backgroundColors?:
            | {
                backgroundColor:
                  | 'left'
                  | 'right'
                  | 'topLeft'
                  | 'topRight'
                  | 'center'
                  | 'centerLeft'
                  | 'centerRight'
                  | 'bottomLeft'
                  | 'bottomRight';
                id?: string | null;
              }[]
            | null;
        };
      };
    };
    projects?: {
      projectsHero: {
        padding?: {
          paddingTop?: ('small' | 'medium' | 'large') | null;
          paddingBottom?: ('small' | 'medium' | 'large') | null;
        };
        heading: string;
        content?: {
          richText?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          links?:
            | {
                link: {
                  label: string;
                  reference?: {
                    relationTo: 'pages';
                    value: string | Page;
                  } | null;
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  url?: string | null;
                  appearance?: ('default' | 'gradient') | null;
                };
                id?: string | null;
              }[]
            | null;
          imageLinks?:
            | {
                imageLink?: {
                  reference?: {
                    relationTo: 'pages';
                    value: string | Page;
                  } | null;
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  url?: string | null;
                  image?: string | Media | null;
                };
                id?: string | null;
              }[]
            | null;
        };
      };
    };
  };
  layout?:
    | (
        | {
            heading?: string | null;
            padding?: {
              paddingTop?: ('small' | 'medium' | 'large') | null;
              paddingBottom?: ('small' | 'medium' | 'large') | null;
            };
            position?: ('left' | 'right') | null;
            content?: {
              richText?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              links?:
                | {
                    link: {
                      label: string;
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      appearance?: ('default' | 'gradient') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              imageLinks?:
                | {
                    imageLink?: {
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      image?: string | Media | null;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            slides?:
              | {
                  projectImage?: string | Media | null;
                  projectImageDark?: string | Media | null;
                  projectImageLight?: string | Media | null;
                  imageType?: boolean | null;
                  slideTitle?: string | null;
                  slideDescription?: string | null;
                  slideUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carouselBlock';
          }
        | {
            heading?: string | null;
            padding?: {
              paddingTop?: ('small' | 'medium' | 'large') | null;
              paddingBottom?: ('small' | 'medium' | 'large') | null;
            };
            position?: ('left' | 'right') | null;
            content?: {
              richText?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              links?:
                | {
                    link: {
                      label: string;
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      appearance?: ('default' | 'gradient') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              imageLinks?:
                | {
                    imageLink?: {
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      image?: string | Media | null;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'emailBlock';
          }
        | {
            heading?: string | null;
            padding?: {
              paddingTop?: ('small' | 'medium' | 'large') | null;
              paddingBottom?: ('small' | 'medium' | 'large') | null;
            };
            position?: ('left' | 'right') | null;
            content?: {
              richText?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              links?:
                | {
                    link: {
                      label: string;
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      appearance?: ('default' | 'gradient') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              imageLinks?:
                | {
                    imageLink?: {
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      image?: string | Media | null;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            skills?:
              | {
                  skillName?: string | null;
                  skillDescription?: string | null;
                  skillImage: string | Media;
                  skillId?: string | null;
                  skillLink?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'skillsBlock';
          }
        | {
            heading?: string | null;
            padding?: {
              paddingTop?: ('small' | 'medium' | 'large') | null;
              paddingBottom?: ('small' | 'medium' | 'large') | null;
            };
            content?: {
              richText?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              links?:
                | {
                    link: {
                      label: string;
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      appearance?: ('default' | 'gradient') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              imageLinks?:
                | {
                    imageLink?: {
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      image?: string | Media | null;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            timelineElements?:
              | {
                  title?: string | null;
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  date?: string | null;
                  icon: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timelineBlock';
          }
        | {
            padding?: {
              paddingTop?: ('small' | 'medium' | 'large') | null;
              paddingBottom?: ('small' | 'medium' | 'large') | null;
            };
            firstProjects?: {
              firstProjectsContent?: {
                heading?: string | null;
                content?: {
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  links?:
                    | {
                        link: {
                          label: string;
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          appearance?: ('default' | 'gradient') | null;
                        };
                        id?: string | null;
                      }[]
                    | null;
                  imageLinks?:
                    | {
                        imageLink?: {
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          image?: string | Media | null;
                        };
                        id?: string | null;
                      }[]
                    | null;
                };
              };
              projectsField?:
                | {
                    projectImage?: string | Media | null;
                    projectImageDark?: string | Media | null;
                    projectImageLight?: string | Media | null;
                    imageType?: boolean | null;
                    projectName?: string | null;
                    projectTeaser?: string | null;
                    projectDescription?: string | null;
                    projectUrl?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            secondProjects?: {
              secondProjectsContent?: {
                heading?: string | null;
                content?: {
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  links?:
                    | {
                        link: {
                          label: string;
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          appearance?: ('default' | 'gradient') | null;
                        };
                        id?: string | null;
                      }[]
                    | null;
                  imageLinks?:
                    | {
                        imageLink?: {
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          image?: string | Media | null;
                        };
                        id?: string | null;
                      }[]
                    | null;
                };
              };
              projectsField?:
                | {
                    projectImage?: string | Media | null;
                    projectImageDark?: string | Media | null;
                    projectImageLight?: string | Media | null;
                    imageType?: boolean | null;
                    projectName?: string | null;
                    projectTeaser?: string | null;
                    projectDescription?: string | null;
                    projectUrl?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            thirdProjects?: {
              thirdProjectsContent?: {
                heading?: string | null;
                content?: {
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  links?:
                    | {
                        link: {
                          label: string;
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          appearance?: ('default' | 'gradient') | null;
                        };
                        id?: string | null;
                      }[]
                    | null;
                  imageLinks?:
                    | {
                        imageLink?: {
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          image?: string | Media | null;
                        };
                        id?: string | null;
                      }[]
                    | null;
                };
              };
              projectsField?:
                | {
                    projectImage?: string | Media | null;
                    projectImageDark?: string | Media | null;
                    projectImageLight?: string | Media | null;
                    imageType?: boolean | null;
                    projectName?: string | null;
                    projectTeaser?: string | null;
                    projectDescription?: string | null;
                    projectUrl?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectsBlock';
          }
      )[]
    | null;
  slug?: string | null;
  author?: (string | null) | User;
  fullTitle?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skillsCollection".
 */
export interface SkillsCollection {
  id: string;
  skills?:
    | {
        skillName?: string | null;
        skillDescription?: string | null;
        skillImage: string | Media;
        skillId?: string | null;
        skillLink?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  linkBlock?: {
    linkBlockLabel?: string | null;
    links?:
      | {
          imageLink?: {
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            url?: string | null;
            image?: string | Media | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  copyrightBlock?: {
    copyrightLabel?: string | null;
    copyrightBody?: string | null;
    linkText?: string | null;
    copyrightLinks?:
      | {
          imageLink?: {
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            url?: string | null;
            image?: string | Media | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}