/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    skillsCollection: SkillsCollection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    skillsCollection: SkillsCollectionSelect<false> | SkillsCollectionSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    footer: Footer;
  };
  globalsSelect: {
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Select an image to use as a video fallback when browsers refuse to play them in iOS low-power mode
   */
  fallback?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'standard' | 'projects';
    standard?: {
      standardHero: {
        padding?: {
          paddingTop?: ('small' | 'medium' | 'large') | null;
          paddingBottom?: ('small' | 'medium' | 'large') | null;
        };
        position?: ('left' | 'right') | null;
        heading: string;
        content?: {
          richText?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          links?:
            | {
                link: {
                  label: string;
                  reference?: {
                    relationTo: 'pages';
                    value: string | Page;
                  } | null;
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  url?: string | null;
                  appearance?: ('default' | 'gradient') | null;
                };
                id?: string | null;
              }[]
            | null;
          imageLinks?:
            | {
                imageLink?: {
                  reference?: {
                    relationTo: 'pages';
                    value: string | Page;
                  } | null;
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  url?: string | null;
                  image?: (string | null) | Media;
                };
                id?: string | null;
              }[]
            | null;
        };
        heroImage: string | Media;
        enableBackgroundColors?: boolean | null;
        backgroundColors?: {
          backgroundColors?:
            | {
                /**
                 * Select the position for the background color
                 */
                backgroundColor:
                  | 'left'
                  | 'right'
                  | 'topLeft'
                  | 'topRight'
                  | 'center'
                  | 'centerLeft'
                  | 'centerRight'
                  | 'bottomLeft'
                  | 'bottomRight';
                id?: string | null;
              }[]
            | null;
        };
      };
    };
    projects?: {
      projectsHero: {
        padding?: {
          paddingTop?: ('small' | 'medium' | 'large') | null;
          paddingBottom?: ('small' | 'medium' | 'large') | null;
        };
        heading: string;
        content?: {
          richText?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          links?:
            | {
                link: {
                  label: string;
                  reference?: {
                    relationTo: 'pages';
                    value: string | Page;
                  } | null;
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  url?: string | null;
                  appearance?: ('default' | 'gradient') | null;
                };
                id?: string | null;
              }[]
            | null;
          imageLinks?:
            | {
                imageLink?: {
                  reference?: {
                    relationTo: 'pages';
                    value: string | Page;
                  } | null;
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  url?: string | null;
                  image?: (string | null) | Media;
                };
                id?: string | null;
              }[]
            | null;
        };
      };
    };
  };
  layout?:
    | (
        | {
            heading?: string | null;
            padding?: {
              paddingTop?: ('small' | 'medium' | 'large') | null;
              paddingBottom?: ('small' | 'medium' | 'large') | null;
            };
            position?: ('left' | 'right') | null;
            content?: {
              richText?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              links?:
                | {
                    link: {
                      label: string;
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      appearance?: ('default' | 'gradient') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              imageLinks?:
                | {
                    imageLink?: {
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      image?: (string | null) | Media;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            slides?:
              | {
                  projectImage?: (string | null) | Media;
                  projectImageDark?: (string | null) | Media;
                  projectImageLight?: (string | null) | Media;
                  imageType?: boolean | null;
                  slideTitle?: string | null;
                  slideDescription?: string | null;
                  slideUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carouselBlock';
          }
        | {
            heading?: string | null;
            padding?: {
              paddingTop?: ('small' | 'medium' | 'large') | null;
              paddingBottom?: ('small' | 'medium' | 'large') | null;
            };
            position?: ('left' | 'right') | null;
            content?: {
              richText?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              links?:
                | {
                    link: {
                      label: string;
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      appearance?: ('default' | 'gradient') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              imageLinks?:
                | {
                    imageLink?: {
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      image?: (string | null) | Media;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'emailBlock';
          }
        | {
            heading?: string | null;
            padding?: {
              paddingTop?: ('small' | 'medium' | 'large') | null;
              paddingBottom?: ('small' | 'medium' | 'large') | null;
            };
            position?: ('left' | 'right') | null;
            content?: {
              richText?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              links?:
                | {
                    link: {
                      label: string;
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      appearance?: ('default' | 'gradient') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              imageLinks?:
                | {
                    imageLink?: {
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      image?: (string | null) | Media;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            skills?:
              | {
                  skillName?: string | null;
                  skillDescription?: string | null;
                  skillImage: string | Media;
                  skillId?: string | null;
                  skillLink?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'skillsBlock';
          }
        | {
            heading?: string | null;
            padding?: {
              paddingTop?: ('small' | 'medium' | 'large') | null;
              paddingBottom?: ('small' | 'medium' | 'large') | null;
            };
            content?: {
              richText?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              links?:
                | {
                    link: {
                      label: string;
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      appearance?: ('default' | 'gradient') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              imageLinks?:
                | {
                    imageLink?: {
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      url?: string | null;
                      image?: (string | null) | Media;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            timelineElements?:
              | {
                  title?: string | null;
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  date?: string | null;
                  icon: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timelineBlock';
          }
        | {
            padding?: {
              paddingTop?: ('small' | 'medium' | 'large') | null;
              paddingBottom?: ('small' | 'medium' | 'large') | null;
            };
            firstProjects?: {
              firstProjectsContent?: {
                heading?: string | null;
                content?: {
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  links?:
                    | {
                        link: {
                          label: string;
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          appearance?: ('default' | 'gradient') | null;
                        };
                        id?: string | null;
                      }[]
                    | null;
                  imageLinks?:
                    | {
                        imageLink?: {
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          image?: (string | null) | Media;
                        };
                        id?: string | null;
                      }[]
                    | null;
                };
              };
              projectsField?:
                | {
                    projectImage?: (string | null) | Media;
                    projectImageDark?: (string | null) | Media;
                    projectImageLight?: (string | null) | Media;
                    imageType?: boolean | null;
                    projectName?: string | null;
                    projectTeaser?: string | null;
                    projectDescription?: string | null;
                    /**
                     * Keep identical to [Slide Url] in any given carousel slide.
                     */
                    projectUrl?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            secondProjects?: {
              secondProjectsContent?: {
                heading?: string | null;
                content?: {
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  links?:
                    | {
                        link: {
                          label: string;
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          appearance?: ('default' | 'gradient') | null;
                        };
                        id?: string | null;
                      }[]
                    | null;
                  imageLinks?:
                    | {
                        imageLink?: {
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          image?: (string | null) | Media;
                        };
                        id?: string | null;
                      }[]
                    | null;
                };
              };
              projectsField?:
                | {
                    projectImage?: (string | null) | Media;
                    projectImageDark?: (string | null) | Media;
                    projectImageLight?: (string | null) | Media;
                    imageType?: boolean | null;
                    projectName?: string | null;
                    projectTeaser?: string | null;
                    projectDescription?: string | null;
                    /**
                     * Keep identical to [Slide Url] in any given carousel slide.
                     */
                    projectUrl?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            thirdProjects?: {
              thirdProjectsContent?: {
                heading?: string | null;
                content?: {
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  links?:
                    | {
                        link: {
                          label: string;
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          appearance?: ('default' | 'gradient') | null;
                        };
                        id?: string | null;
                      }[]
                    | null;
                  imageLinks?:
                    | {
                        imageLink?: {
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          image?: (string | null) | Media;
                        };
                        id?: string | null;
                      }[]
                    | null;
                };
              };
              projectsField?:
                | {
                    projectImage?: (string | null) | Media;
                    projectImageDark?: (string | null) | Media;
                    projectImageLight?: (string | null) | Media;
                    imageType?: boolean | null;
                    projectName?: string | null;
                    projectTeaser?: string | null;
                    projectDescription?: string | null;
                    /**
                     * Keep identical to [Slide Url] in any given carousel slide.
                     */
                    projectUrl?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectsBlock';
          }
      )[]
    | null;
  /**
   * Let Payload automatically generate this for you; do not edit.
   */
  slug?: string | null;
  slugLock?: boolean | null;
  author?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skillsCollection".
 */
export interface SkillsCollection {
  id: string;
  skills?:
    | {
        skillName?: string | null;
        skillDescription?: string | null;
        skillImage: string | Media;
        skillId?: string | null;
        skillLink?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'skillsCollection';
        value: string | SkillsCollection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  fallback?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        standard?:
          | T
          | {
              standardHero?:
                | T
                | {
                    padding?:
                      | T
                      | {
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                    position?: T;
                    heading?: T;
                    content?:
                      | T
                      | {
                          richText?: T;
                          links?:
                            | T
                            | {
                                link?:
                                  | T
                                  | {
                                      label?: T;
                                      reference?: T;
                                      type?: T;
                                      newTab?: T;
                                      url?: T;
                                      appearance?: T;
                                    };
                                id?: T;
                              };
                          imageLinks?:
                            | T
                            | {
                                imageLink?:
                                  | T
                                  | {
                                      reference?: T;
                                      type?: T;
                                      newTab?: T;
                                      url?: T;
                                      image?: T;
                                    };
                                id?: T;
                              };
                        };
                    heroImage?: T;
                    enableBackgroundColors?: T;
                    backgroundColors?:
                      | T
                      | {
                          backgroundColors?:
                            | T
                            | {
                                backgroundColor?: T;
                                id?: T;
                              };
                        };
                  };
            };
        projects?:
          | T
          | {
              projectsHero?:
                | T
                | {
                    padding?:
                      | T
                      | {
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                    heading?: T;
                    content?:
                      | T
                      | {
                          richText?: T;
                          links?:
                            | T
                            | {
                                link?:
                                  | T
                                  | {
                                      label?: T;
                                      reference?: T;
                                      type?: T;
                                      newTab?: T;
                                      url?: T;
                                      appearance?: T;
                                    };
                                id?: T;
                              };
                          imageLinks?:
                            | T
                            | {
                                imageLink?:
                                  | T
                                  | {
                                      reference?: T;
                                      type?: T;
                                      newTab?: T;
                                      url?: T;
                                      image?: T;
                                    };
                                id?: T;
                              };
                        };
                  };
            };
      };
  layout?:
    | T
    | {
        carouselBlock?:
          | T
          | {
              heading?: T;
              padding?:
                | T
                | {
                    paddingTop?: T;
                    paddingBottom?: T;
                  };
              position?: T;
              content?:
                | T
                | {
                    richText?: T;
                    links?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                label?: T;
                                reference?: T;
                                type?: T;
                                newTab?: T;
                                url?: T;
                                appearance?: T;
                              };
                          id?: T;
                        };
                    imageLinks?:
                      | T
                      | {
                          imageLink?:
                            | T
                            | {
                                reference?: T;
                                type?: T;
                                newTab?: T;
                                url?: T;
                                image?: T;
                              };
                          id?: T;
                        };
                  };
              slides?:
                | T
                | {
                    projectImage?: T;
                    projectImageDark?: T;
                    projectImageLight?: T;
                    imageType?: T;
                    slideTitle?: T;
                    slideDescription?: T;
                    slideUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        emailBlock?:
          | T
          | {
              heading?: T;
              padding?:
                | T
                | {
                    paddingTop?: T;
                    paddingBottom?: T;
                  };
              position?: T;
              content?:
                | T
                | {
                    richText?: T;
                    links?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                label?: T;
                                reference?: T;
                                type?: T;
                                newTab?: T;
                                url?: T;
                                appearance?: T;
                              };
                          id?: T;
                        };
                    imageLinks?:
                      | T
                      | {
                          imageLink?:
                            | T
                            | {
                                reference?: T;
                                type?: T;
                                newTab?: T;
                                url?: T;
                                image?: T;
                              };
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        skillsBlock?:
          | T
          | {
              heading?: T;
              padding?:
                | T
                | {
                    paddingTop?: T;
                    paddingBottom?: T;
                  };
              position?: T;
              content?:
                | T
                | {
                    richText?: T;
                    links?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                label?: T;
                                reference?: T;
                                type?: T;
                                newTab?: T;
                                url?: T;
                                appearance?: T;
                              };
                          id?: T;
                        };
                    imageLinks?:
                      | T
                      | {
                          imageLink?:
                            | T
                            | {
                                reference?: T;
                                type?: T;
                                newTab?: T;
                                url?: T;
                                image?: T;
                              };
                          id?: T;
                        };
                  };
              skills?:
                | T
                | {
                    skillName?: T;
                    skillDescription?: T;
                    skillImage?: T;
                    skillId?: T;
                    skillLink?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timelineBlock?:
          | T
          | {
              heading?: T;
              padding?:
                | T
                | {
                    paddingTop?: T;
                    paddingBottom?: T;
                  };
              content?:
                | T
                | {
                    richText?: T;
                    links?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                label?: T;
                                reference?: T;
                                type?: T;
                                newTab?: T;
                                url?: T;
                                appearance?: T;
                              };
                          id?: T;
                        };
                    imageLinks?:
                      | T
                      | {
                          imageLink?:
                            | T
                            | {
                                reference?: T;
                                type?: T;
                                newTab?: T;
                                url?: T;
                                image?: T;
                              };
                          id?: T;
                        };
                  };
              timelineElements?:
                | T
                | {
                    title?: T;
                    richText?: T;
                    date?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projectsBlock?:
          | T
          | {
              padding?:
                | T
                | {
                    paddingTop?: T;
                    paddingBottom?: T;
                  };
              firstProjects?:
                | T
                | {
                    firstProjectsContent?:
                      | T
                      | {
                          heading?: T;
                          content?:
                            | T
                            | {
                                richText?: T;
                                links?:
                                  | T
                                  | {
                                      link?:
                                        | T
                                        | {
                                            label?: T;
                                            reference?: T;
                                            type?: T;
                                            newTab?: T;
                                            url?: T;
                                            appearance?: T;
                                          };
                                      id?: T;
                                    };
                                imageLinks?:
                                  | T
                                  | {
                                      imageLink?:
                                        | T
                                        | {
                                            reference?: T;
                                            type?: T;
                                            newTab?: T;
                                            url?: T;
                                            image?: T;
                                          };
                                      id?: T;
                                    };
                              };
                        };
                    projectsField?:
                      | T
                      | {
                          projectImage?: T;
                          projectImageDark?: T;
                          projectImageLight?: T;
                          imageType?: T;
                          projectName?: T;
                          projectTeaser?: T;
                          projectDescription?: T;
                          projectUrl?: T;
                          id?: T;
                        };
                  };
              secondProjects?:
                | T
                | {
                    secondProjectsContent?:
                      | T
                      | {
                          heading?: T;
                          content?:
                            | T
                            | {
                                richText?: T;
                                links?:
                                  | T
                                  | {
                                      link?:
                                        | T
                                        | {
                                            label?: T;
                                            reference?: T;
                                            type?: T;
                                            newTab?: T;
                                            url?: T;
                                            appearance?: T;
                                          };
                                      id?: T;
                                    };
                                imageLinks?:
                                  | T
                                  | {
                                      imageLink?:
                                        | T
                                        | {
                                            reference?: T;
                                            type?: T;
                                            newTab?: T;
                                            url?: T;
                                            image?: T;
                                          };
                                      id?: T;
                                    };
                              };
                        };
                    projectsField?:
                      | T
                      | {
                          projectImage?: T;
                          projectImageDark?: T;
                          projectImageLight?: T;
                          imageType?: T;
                          projectName?: T;
                          projectTeaser?: T;
                          projectDescription?: T;
                          projectUrl?: T;
                          id?: T;
                        };
                  };
              thirdProjects?:
                | T
                | {
                    thirdProjectsContent?:
                      | T
                      | {
                          heading?: T;
                          content?:
                            | T
                            | {
                                richText?: T;
                                links?:
                                  | T
                                  | {
                                      link?:
                                        | T
                                        | {
                                            label?: T;
                                            reference?: T;
                                            type?: T;
                                            newTab?: T;
                                            url?: T;
                                            appearance?: T;
                                          };
                                      id?: T;
                                    };
                                imageLinks?:
                                  | T
                                  | {
                                      imageLink?:
                                        | T
                                        | {
                                            reference?: T;
                                            type?: T;
                                            newTab?: T;
                                            url?: T;
                                            image?: T;
                                          };
                                      id?: T;
                                    };
                              };
                        };
                    projectsField?:
                      | T
                      | {
                          projectImage?: T;
                          projectImageDark?: T;
                          projectImageLight?: T;
                          imageType?: T;
                          projectName?: T;
                          projectTeaser?: T;
                          projectDescription?: T;
                          projectUrl?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  slugLock?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skillsCollection_select".
 */
export interface SkillsCollectionSelect<T extends boolean = true> {
  skills?:
    | T
    | {
        skillName?: T;
        skillDescription?: T;
        skillImage?: T;
        skillId?: T;
        skillLink?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  linkBlock?: {
    linkBlockLabel?: string | null;
    links?:
      | {
          imageLink?: {
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            url?: string | null;
            image?: (string | null) | Media;
          };
          id?: string | null;
        }[]
      | null;
  };
  copyrightBlock?: {
    copyrightLabel?: string | null;
    copyrightBody?: string | null;
    linkText?: string | null;
    copyrightLinks?:
      | {
          imageLink?: {
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            url?: string | null;
            image?: (string | null) | Media;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  linkBlock?:
    | T
    | {
        linkBlockLabel?: T;
        links?:
          | T
          | {
              imageLink?:
                | T
                | {
                    reference?: T;
                    type?: T;
                    newTab?: T;
                    url?: T;
                    image?: T;
                  };
              id?: T;
            };
      };
  copyrightBlock?:
    | T
    | {
        copyrightLabel?: T;
        copyrightBody?: T;
        linkText?: T;
        copyrightLinks?:
          | T
          | {
              imageLink?:
                | T
                | {
                    reference?: T;
                    type?: T;
                    newTab?: T;
                    url?: T;
                    image?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}